### ISSUE TITLE
Better self role management

### ISSUE THREAD

**Issue by MarkusKgit** [MarkusKgit/MonkeyBot#241]
Consolidate the existing self role management methods by using the new Buttons/Drop Down feature

`!addrole` should present a drop down of roles you can assign to yourself. Upon clicking one item the user should get that role. On the other hand `!removerole` should present a dropdown list of roles the user already has. Upon click the role should get removed from the user.

Similarly an admin can add a role dropdown to any message, e.g. on the welcome page (like the current role "buttons"). So users can pick roles at any time without having to use the `!addrole` command first.

**Comment by MarkusKgit** [comment]
Sure, I'd apreciate it!

**Comment by ashwin003** [comment]
@MarkusKgit I've managed to implement the dropdown for assigning and revoking roles by using the `!addrole` and `!removerole`

![image](https://user-images.githubusercontent.com/12110372/136599574-f6f8ff6c-d47e-4bfb-9fdb-815fb7edf3c5.png)

> Similarly an admin can add a role dropdown to any message, e.g. on the welcome page (like the current role "buttons"). So users can pick roles at any time without having to use the `!addrole` command first.

What do I need to do for this scenario?

**Comment by MarkusKgit** [comment]
Sweet,

the second part should work like the exisiting role button links. They are handled by this service  https://github.com/MarkusKgit/MonkeyBot/blob/1be2e55bdb9dc8464ddea0704240f0201a9f99c2/MonkeyBot/Modules/RoleManagement/RoleButtonService.cs#L16 
and is set up by
https://github.com/MarkusKgit/MonkeyBot/blob/1be2e55bdb9dc8464ddea0704240f0201a9f99c2/MonkeyBot/Modules/RoleManagement/RoleButtonsModule.cs#L18
But instead of linking an emoji, it would be better to just add either a drop down option or a new button with the name of the role (and the role icon if it exists)
But the handler of the buttons must survive a Bot restart.
Let me know if you need more guidance

**Comment by MarkusKgit** [comment]
Done by #252
