### ISSUE TITLE
Enhance Polls

### ISSUE THREAD

**Issue by MarkusKgit** [MarkusKgit/MonkeyBot#242]
Enhance the poll feature by using actual buttons instead of reactions

**Comment by MarkusKgit** [comment]
Sure thing :+1:

**Comment by Laxynium** [comment]
Hey, I couldn't find time to implement it, but I should be able to do this today.

**Comment by Laxynium** [comment]
I have created PR https://github.com/MarkusKgit/MonkeyBot/pull/261.
