### ISSUE TITLE
Bot greeting

### ISSUE THREAD

**Issue by MarkusKgit** [MarkusKgit/MonkeyBot#247]
Add a nicely formatted message for any new guild the Bot joins. It should contain some instructions for first use, a link to the Documentation and the help Discord Guild

**Comment by Laxynium** [comment]
Hi, could I start working on it?

**Comment by MarkusKgit** [comment]
Hi, yes sure - I would appreciate it!

There could be your starting point:

https://github.com/MarkusKgit/MonkeyBot/blob/ad48984931d4d4cdc68f004ad388fe00d32943d9/MonkeyBot/Initializer.cs#L298

Feel free to PR early, then we can discuss what to add exactly but you can start with the mentioned points in the issue. You could also have a look at the Guild Entity to pick out some important configuration (like Prefix or Welcome Message)

**Comment by Laxynium** [comment]
Ok, thanks.

**Comment by Laxynium** [comment]
I have added PR https://github.com/MarkusKgit/MonkeyBot/pull/250.
