### ISSUE TITLE
Nullable reference types

### ISSUE THREAD

**Issue by MarkusKgit** [MarkusKgit/MonkeyBot#50]
Consider using the new nullable reference types features for more runtime robustness. 
To get started:

- https://devblogs.microsoft.com/dotnet/try-out-nullable-reference-types/
- https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references

**Comment by Excolo** [comment]
I'd like to give this a go. 

Would you prefer to have the compilation fail when potential null-references aren't handled or are warnings sufficient?

**Comment by MarkusKgit** [comment]
Hi @Excolo, I would be pleased if you want to give it a shot. For now I'd prefer warnings. 
Feel free to PR early, so we can discuss the design changes right away.
